### ISSUE TITLE
Add some examples or use-cases

### ISSUE THREAD

**Issue by troglobit** [maandree/bus#1]
This was a very nice surprise, looks almost exactly like what I need!  But how do I use it?
Could you perhaps add a couple of simple example use-cases to the README?

**Comment by maandree** [comment]
Sure.

There are some man pages you could look at until then.

**Comment by troglobit** [comment]
Thanks!  Will do. 

Maybe I should add, I mean some C example use-cases. (Sorry!)

**Comment by maandree** [comment]
> Maybe I should add, I mean some C example use-cases.

I gathered. It is basically the only thing you have on your account.

I have added one shell example and one C example.
The rationale here, is users probably want to create
buses from the profile file, and use broadcast messages
from small shell scripts, but you probably do not want
to use the commands from your programs.

**Comment by troglobit** [comment]
Yeah, what I really wanted was a very light-weight system message bus for my [finit](https://github.com/troglobit/finit) project.  But I also gathered that for such an awesome little project like yours, you'd benefit from a couple more examples to draw attention to your project.

Cheers!
