### ISSUE TITLE
Possible to get a non-blocking file descriptor?

### ISSUE THREAD

**Issue by troglobit** [maandree/bus#2]
Any way to get a file descriptor for polling? Non-blocking preferably.

**Comment by maandree** [comment]
I have plans to implement non-blocking later on.
I also have plans to add a polling alternative to
`bus_read`. When this is implemented,
`fopencookie` (_GNU_SOURCE) could be used
to get a `FILE *` for polling, but I do not know how
to create a file descriptor, but I would be very
interested in that is it would allow for things like
`select`.

With the current API however, there is not
really any convinient way.

**Comment by troglobit** [comment]
Sounds cool, never even heard about `fopencookie()` before! :)

Ever thought about using [eventfd](http://man7.org/linux/man-pages/man2/eventfd.2.html)?

**Comment by maandree** [comment]
I will read up on it.

**Comment by maandree** [comment]
In version 3.0 `bus_poll` will be introduced. `bus_poll` supports non-blocking.
But I don't think there is any way to get a file descriptor, unless there is some
way to get a file descriptor for a System V semaphore array.

However. If you want to use it internally in finit, you could create an eventfd
in init, and replace `bus_write` with a function that writes to eventfd directly
before the `t(write_semaphore(bus, Q, 0));` line. Then the listeners could
use `epoll`, `poll` or `select` over the eventfd, and call `bus_poll` when the
eventfd is touched.

**Comment by troglobit** [comment]
Interesting, I was about to propose replacing the SysV semaphore with eventfd, but you're right,
maybe the semid kan be used as a file descriptor?  I have a vague recollection of using it in a previous project.

**Comment by maandree** [comment]
I don't think semid can be used as a file descriptor. But if you find a way, let me now. Closing until then, as I don't think this can be fixed.
